### ISSUE TITLE
Bug: Empty link []() causes a crash

### ISSUE THREAD

**Issue by Joepocalyptic** [mikepenz/multiplatform-markdown-renderer#166]
## About this issue

Using the `Markdown` composable with an input string that contains an empty link syntax `[]()` causes a crash on Android:
```
FATAL EXCEPTION: main
Process: AppProcessHere, PID: 30037
java.lang.IllegalStateException: Nothing to pop.
        at androidx.compose.ui.text.AnnotatedString$Builder.pop(AnnotatedString.kt:610)
        at com.mikepenz.markdown.compose.elements.MarkdownParagraphKt.MarkdownParagraph(MarkdownParagraph.kt:21)
        at com.mikepenz.markdown.compose.components.ComposableSingletons$MarkdownComponentsKt$lambda-14$1.invoke(MarkdownComponents.kt:171)
        at com.mikepenz.markdown.compose.components.ComposableSingletons$MarkdownComponentsKt$lambda-14$1.invoke(MarkdownComponents.kt:170)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:139)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
```
Sample:
```kotlin
Markdown(
  content = "Example string []() example string"
)
```

## Details
- [X] Used library version - 0.21.0
- [X] Used platform - Android
- [ ] Used support library version - N/A
- [X] Used gradle build tools version - Gradle 8.7 w/ AGP 8.5.0
- [X] Used tooling / Android Studio version - Koala 2024.1.1
- [X] Other used libraries, potential conflicting libraries - Kotlin 2.0.0 w/ Compose Multiplatform 1.6.11

## Checklist

- [X] Searched for [similar issues](https://github.com/mikepenz/multiplatform-markdown-renderer/issues)
- [X] Checked out the [sample application](https://github.com/mikepenz/multiplatform-markdown-renderer/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/README.md)
- [X] Checked out the [CHANGELOG](https://github.com/mikepenz/multiplatform-markdown-renderer/releases)
- [X] Read the [FAQ](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/FAQ.md)
- [X] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
Thank you very much for the report!
